### ISSUE TITLE
Logstash connection failure

### ISSUE THREAD

**Issue by gromit6891** [kiwiz/411#2]
Firstly - Great project!
Re. config.php
I have a time based index 'logstash-apache-*' in ES. I have tried logstash, logstash-apache-, logstash-2016.08.12 in config.php but still get a Failure in the health screen. The alerts section works fine.
Any debug logging available?

'logstash' => [
        'hosts' => ['http://192.168.1.196:9200'],
        'index_hosts' => [],
        'index' => 'logstash-apache-',
        'date_based' => true,
        'date_field' => '@timestamp',
        'src_url' => null,

Curl request:
curl http://192.168.1.196:9200/logstash-apache-2016.08.14?pretty
{
  "logstash-apache-2016.08.14" : {
    "aliases" : { },
    "mappings" : {
      "_default_" : {
        "_all" : {
          "enabled" : true,
          "omit_norms" : true
.....

**Comment by kiwiz** [comment]
Thanks!

For the index name, I believe `logstash-apache` should do the job.
You can see errors in the standard apache error logs (varies depending on distro: `error_log`, `info.log`, etc).

**Comment by gromit6891** [comment]
Thanks! I must have tried everything but that.

**Comment by christophwischow** [comment]
Hey,

do u solved the issue @gromit6891 ?

I guess i got the same error, hosting 411 on one node and elastic and logstash on a second one.
Healthmonitor for Logstash is read and i can't find something usefull inside the apache error.log

**Comment by kiwiz** [comment]
@christophwischow Are you still having this problem? If so, can you create a new issue with more details about your config and setup?

**Comment by christophwischow** [comment]
Gladly I solved the issue and got it up and running.

**Comment by kar3ousse** [comment]
@christophwischow how did you resolve your problem , i have the same issue .
I create a new search but when i try to test or to run , i have always No Result . 
When i use elasticsearch for searching with the same parametres i have a result .
I thing that the problem in config.php . Please help me.
