### ISSUE TITLE
Demo Site is down

### ISSUE THREAD

**Issue by worldworm** [kiwiz/411#211]
your demo page is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by worldworm** [comment]
ping @etsy

**Comment by worldworm** [comment]
Unfortunately the demopage was removed from awesome-selfhosted due to inactivity. You can add this url at any time should it become active again.
Thanks for your understanding!

https://github.com/awesome-selfhosted/awesome-selfhosted
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/1767
https://github.com/awesome-selfhosted/awesome-selfhosted/pull/1838

**Comment by dimo414** [comment]
Not clear why this was closed, the demo URL in the project description is still dead. The most recent build also appears to have failed, and the project hasn't been touched in some time. Is it dead?

@kiwiz @coykitten
